-- ARITHMETIC FUNCTIONS IN MYSQL
-- ABS(), ACOS(), ASIN(), ATAN(), ATAN2(), CEILING(), COS(), COT(), DEGREES(), EXP(), FLOOR(), LOG(), LOG10(), MOD(), PI(), POW(), RADIANS(), RAND()-> any number b/w 0 and 1, ROUND(), SIGN()->same as SIGNUM FUNCTION, SIN(), SQRT(), TAN(), TRUNCATE()
SELECT ABS(5-6) AS ABS_DIFF;
-- BELOW ROUND FUNCTIONS RETURNS AN INTEGER
SELECT ROUND(5.6);
SELECT ROUND(5.4);
SELECT FLOOR(5.8);
SELECT CEIL(5.3);
SELECT EXP(2);
-- BELOW ROUND FUNCTIONS RETURNS A FLOAT VALUE UPTO 3 DECIMAL PLACES
SELECT ROUND(PI(), 3);
SELECT POW(2, 3.1);
SELECT SQRT(4.55);
SELECT RAND();
SELECT SIGN(52.6); -- RETURNS 1
SELECT SIGN(-5.6); -- RETURNS -1
SELECT SIGN(0); -- RETURNS 0
